// <auto-generated />
using System;
using ApplicationContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MonitoringSystemPCGWebAPI.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20260419080348_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.ActivityType", b =>
                {
                    b.Property<int?>("ActivityTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("ActivityTypeId"));

                    b.Property<string>("ActivityTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsMandatoryLeave")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxCredits")
                        .HasColumnType("int");

                    b.Property<int?>("ResetMonths")
                        .HasColumnType("int");

                    b.HasKey("ActivityTypeId");

                    b.ToTable("ActivityType");
                });

            modelBuilder.Entity("Models.Department", b =>
                {
                    b.Property<int?>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("DepartmentId"));

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentId");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("Models.EmailEteCommunication", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<DateTime?>("AccessedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CommunicationToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpiryDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsAccessed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("NextEte")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PersonnelId")
                        .HasColumnType("int");

                    b.Property<int?>("RemainingDays")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Response")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResponseDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SentDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SupportingDocument")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PersonnelId");

                    b.ToTable("EmailEteCommunication");
                });

            modelBuilder.Entity("Models.EnlistmentRecord", b =>
                {
                    b.Property<int?>("EnlistmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("EnlistmentId"));

                    b.Property<int?>("ContractYears")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EnlistmentEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EnlistmentStart")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PersonnelId")
                        .HasColumnType("int");

                    b.Property<bool?>("ReenlistmentFlag")
                        .HasColumnType("bit");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EnlistmentId");

                    b.HasIndex("PersonnelId");

                    b.ToTable("EnlistmentRecord");
                });

            modelBuilder.Entity("Models.LeaveTypes", b =>
                {
                    b.Property<int?>("LeaveTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("LeaveTypeID"));

                    b.Property<int?>("AccrualPerMonth")
                        .HasColumnType("int");

                    b.Property<bool?>("Accumulation")
                        .HasColumnType("bit");

                    b.Property<string>("LeaveName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaxPerPeriod")
                        .HasColumnType("int");

                    b.Property<string>("ResetType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LeaveTypeID");

                    b.ToTable("LeaveTypes");
                });

            modelBuilder.Entity("Models.OtpVerifications", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("OtpCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OtpVerifications");
                });

            modelBuilder.Entity("Models.Personnel", b =>
                {
                    b.Property<int?>("PersonnelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("PersonnelId"));

                    b.Property<DateTime?>("DateEnlisted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateEnteredService")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfLastPromotion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmploymentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Profile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RankId")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PersonnelId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("RankId");

                    b.HasIndex("UserId");

                    b.ToTable("Personnel");
                });

            modelBuilder.Entity("Models.PersonnelActivity", b =>
                {
                    b.Property<int?>("PersonnelActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("PersonnelActivityId"));

                    b.Property<int?>("ActivityTypeId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Days")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsFullyApproved")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsWarningSent")
                        .HasColumnType("bit");

                    b.Property<int?>("PersonnelId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Result")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonnelActivityId");

                    b.HasIndex("ActivityTypeId");

                    b.HasIndex("PersonnelId");

                    b.ToTable("PersonnelActivity");
                });

            modelBuilder.Entity("Models.PersonnelDutyLogs", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("PersonnelId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PersonnelId");

                    b.ToTable("PersonnelDutyLogs");
                });

            modelBuilder.Entity("Models.PersonnelPromotion", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<int?>("PersonnelId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PromotionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PersonnelId");

                    b.ToTable("PersonnelPromotion");
                });

            modelBuilder.Entity("Models.Rank", b =>
                {
                    b.Property<int?>("RankId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("RankId"));

                    b.Property<int?>("RankCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("RankCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RankLevel")
                        .HasColumnType("int");

                    b.Property<string>("RankName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RankId");

                    b.HasIndex("RankCategoryId");

                    b.HasIndex("RankLevel")
                        .IsUnique()
                        .HasFilter("[RankLevel] IS NOT NULL");

                    b.ToTable("Rank");
                });

            modelBuilder.Entity("Models.RankCategory", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("Casing")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RankCategory");
                });

            modelBuilder.Entity("Models.Role", b =>
                {
                    b.Property<int?>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("RoleId"));

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("Models.Sidebar", b =>
                {
                    b.Property<int?>("SidebarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("SidebarId"));

                    b.Property<string>("SidebarName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SidebarId");

                    b.ToTable("Sidebar");
                });

            modelBuilder.Entity("Models.SidebarRoleMapping", b =>
                {
                    b.Property<int?>("SidebarRoleMappingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("SidebarRoleMappingId"));

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<int?>("SidebarId")
                        .HasColumnType("int");

                    b.HasKey("SidebarRoleMappingId");

                    b.ToTable("SidebarRoleMapping");
                });

            modelBuilder.Entity("Models.Usertbl", b =>
                {
                    b.Property<int?>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("UserId"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HashedPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Usertbl");
                });

            modelBuilder.Entity("Models.EmailEteCommunication", b =>
                {
                    b.HasOne("Models.Personnel", "Personnel")
                        .WithMany()
                        .HasForeignKey("PersonnelId");

                    b.Navigation("Personnel");
                });

            modelBuilder.Entity("Models.EnlistmentRecord", b =>
                {
                    b.HasOne("Models.Personnel", null)
                        .WithMany("EnlistmentRecords")
                        .HasForeignKey("PersonnelId");
                });

            modelBuilder.Entity("Models.Personnel", b =>
                {
                    b.HasOne("Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.HasOne("Models.Rank", "Rank")
                        .WithMany()
                        .HasForeignKey("RankId");

                    b.HasOne("Models.Usertbl", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Department");

                    b.Navigation("Rank");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Models.PersonnelActivity", b =>
                {
                    b.HasOne("Models.ActivityType", "ActivityType")
                        .WithMany()
                        .HasForeignKey("ActivityTypeId");

                    b.HasOne("Models.Personnel", "Personnel")
                        .WithMany("PersonnelActivities")
                        .HasForeignKey("PersonnelId");

                    b.Navigation("ActivityType");

                    b.Navigation("Personnel");
                });

            modelBuilder.Entity("Models.PersonnelDutyLogs", b =>
                {
                    b.HasOne("Models.Personnel", "Personnel")
                        .WithMany()
                        .HasForeignKey("PersonnelId");

                    b.Navigation("Personnel");
                });

            modelBuilder.Entity("Models.PersonnelPromotion", b =>
                {
                    b.HasOne("Models.Personnel", null)
                        .WithMany("PersonnelPromotions")
                        .HasForeignKey("PersonnelId");
                });

            modelBuilder.Entity("Models.Rank", b =>
                {
                    b.HasOne("Models.RankCategory", "RankCategory")
                        .WithMany()
                        .HasForeignKey("RankCategoryId");

                    b.Navigation("RankCategory");
                });

            modelBuilder.Entity("Models.Personnel", b =>
                {
                    b.Navigation("EnlistmentRecords");

                    b.Navigation("PersonnelActivities");

                    b.Navigation("PersonnelPromotions");
                });
#pragma warning restore 612, 618
        }
    }
}
